=== LimeLinux/Packages/pisi-spec.dtd
<!-- Document Type Declaration file for PISI pspec.xml files -->
<!-- http://www.pardus.org.tr/projeler/pisi/ -->

<!ELEMENT PISI (Source,Package+,History)>

<!-- Source Section -->

<!ELEMENT Source (
	#PCDATA |
	Name |
	Homepage |
	Icon |
	Packager |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	Archive |
	Patches |
	BuildDependencies
)*>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT Homepage (#PCDATA)>

<!ELEMENT Icon (#PCDATA)>

<!ELEMENT Packager (Name, Email)>
<!ELEMENT Email (#PCDATA)>

<!ELEMENT License (#PCDATA)>

<!ELEMENT IsA (#PCDATA)>

<!ELEMENT PartOf (#PCDATA)>

<!ELEMENT Summary (#PCDATA)>
<!ATTLIST Summary xml:lang CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description xml:lang CDATA #IMPLIED>

<!ELEMENT Archive (#PCDATA)>
<!ATTLIST Archive sha1sum CDATA #REQUIRED>
<!-- NOTE: we can limit possible types here to the ones that pisi know -->
<!ATTLIST Archive type CDATA #REQUIRED>

<!ELEMENT BuildDependencies (Dependency*)>

<!ELEMENT Dependency (#PCDATA)>
<!ATTLIST Dependency versionFrom CDATA #IMPLIED>
<!ATTLIST Dependency versionTo CDATA #IMPLIED>
<!ATTLIST Dependency version CDATA #IMPLIED>
<!ATTLIST Dependency releaseFrom CDATA #IMPLIED>
<!ATTLIST Dependency releaseTo CDATA #IMPLIED>
<!ATTLIST Dependency release CDATA #IMPLIED>

<!ELEMENT Patches (Patch*)>

<!ELEMENT Patch (#PCDATA)>
<!ATTLIST Patch compressionType CDATA #IMPLIED>
<!ATTLIST Patch level CDATA #IMPLIED>
<!ATTLIST Patch target CDATA #IMPLIED>


<!-- Package Section -->

<!ELEMENT Package (
	#PCDATA |
	Name |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	RuntimeDependencies |
	Files |
	Conflicts |
	Replaces |
	AdditionalFiles |
	Provides
)*>

<!ELEMENT Provides (COMAR)+>
<!ELEMENT COMAR (#PCDATA)>
<!ATTLIST COMAR script CDATA #IMPLIED>

<!ELEMENT Conflicts (Package)+>
<!-- we have a problem here, this Package tag only contains a package name
while dtd treats this as another Package section, who said dtd doesnt
suck anyway -->
<!ATTLIST Package versionFrom CDATA #IMPLIED>
<!ATTLIST Package versionTo CDATA #IMPLIED>
<!ATTLIST Package version CDATA #IMPLIED>
<!ATTLIST Package releaseFrom CDATA #IMPLIED>
<!ATTLIST Package releaseTo CDATA #IMPLIED>
<!ATTLIST Package release CDATA #IMPLIED>

<!ELEMENT Replaces (Package)+>

<!ELEMENT AdditionalFiles (AdditionalFile+)>
<!ELEMENT AdditionalFile (#PCDATA)>
<!ATTLIST AdditionalFile target CDATA #REQUIRED>
<!ATTLIST AdditionalFile permission CDATA #IMPLIED>
<!ATTLIST AdditionalFile owner CDATA #IMPLIED>

<!ELEMENT RuntimeDependencies (Dependency*)>

<!ELEMENT Files (Path)+>

<!ELEMENT Path (#PCDATA)>
<!-- NOTE: is this list correct? -->
<!ATTLIST Path fileType
	(executable|library|data|config|doc|man|info|localedata|header)
	#REQUIRED>
<!ATTLIST Path permanent (false|true) #IMPLIED>


<!-- History Section -->

<!ELEMENT History (Update+)>

<!ELEMENT Update (#PCDATA | Date | Version | Comment | Name | Email)*>
<!ATTLIST Update release CDATA #REQUIRED>
<!ATTLIST Update type (security|bug) #IMPLIED>

<!ELEMENT Date (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT Comment (#PCDATA)>

=== LimeLinux/Packages/x11/library/libglvnd/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>libglvnd</Name>
        <Homepage>https://github.com/NVIDIA/libglvnd</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>BSD-like</License>
        <IsA>Libry</IsA>
        <Summary>the GL Vendor-Neutral Dispatch library</Summary>
        <Description>This is a work-in-progress implementation of the vendor-neutral dispatch layer for arbitrating OpenGL API calls between multiple vendors on a per-screen basis, as described by Andy Ritger's OpenGL ABI proposal</Description>
        <Archive sha1sum="3fec0e132b17cc5a3d48288f086eea3666ed0ecb" type="targz">https://github.com/NVIDIA/libglvnd/archive/v1.0.0.tar.gz</Archive>
        <BuildDependencies>
            <Dependency>mesa</Dependency>
            <Dependency>python</Dependency>
            <Dependency>libXext</Dependency>
        </BuildDependencies>
    </Source>
    <Package>
        <Name>libglvnd</Name>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib/</Path>
            <Path fileType="data">/usr/include/*</Path>
            <Path fileType="data">/usr/lib/pkgconfig/</Path>
            <Path fileType="doc">/usr/share/*</Path>
        </Files>
    </Package>
    <History>
        <Update release="3">
            <Date>2017-01-21</Date>
            <Version>1.0.0</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/desktop/mate/base/mate-calc/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>mate-calc</Name>
        <Homepage>http://www.mate-desktop.org</Homepage>
        <Packager>
            <Name>Ali Murat Algül</Name>
            <Email>alimuratgulle@limelinux.com</Email>
        </Packager>
        <License>MIT</License>
        <License>GPLv2+</License>
        <License>LGPLv2+</License>
        <Icon>desktop</Icon>
        <IsA>app:gui</IsA>
        <Summary>Calculator for the Mate desktop environment</Summary>
        <Description>mate-calc, Mate masaüstü için hesap makinesi.</Description>
        <Archive sha1sum="6ae665c68d492ef965d0b7f7bdd0e58318cf75ba" type="tarxz">http://pub.mate-desktop.org/releases/1.17/mate-calc-1.17.0.tar.xz</Archive>
        <BuildDependencies>
            <Dependency>gtk3</Dependency>
            <Dependency>libxslt</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>mate-calc</Name>
        <RuntimeDependencies>
            <Dependency>gtk3</Dependency>            
        </RuntimeDependencies>
        <Files>
            <Path fileType="bin">/usr/bin</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="data">/usr/share/man</Path>
            <Path fileType="data">/usr/share/help</Path>
            <Path fileType="data">/usr/share/glib-2.0</Path>
            <Path fileType="data">/usr/share/mate-calc</Path>
            <Path fileType="data">/usr/share/appdata/</Path>
            <Path fileType="data">/usr/share/applications</Path>
            <Path fileType="localedata">/usr/share/locale</Path>
        </Files>
    </Package>

    <History>
	    <Update release="2">
            <Date>2017-01-12</Date>
            <Version>1.17.0</Version>
            <Comment>First Release</Comment>
            <Name>Ali Murat Algül</Name>
            <Email>alimuratgulle@limelinux.com</Email>
        </Update>
        <Update release="1">
            <Date>2017-01-12</Date>
            <Version>1.17.0</Version>
            <Comment>First Release</Comment>
            <Name>Ali Murat Algül</Name>
            <Email>alimuratgulle@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/programming/library/mozjs38/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>mozjs38</Name>
        <Homepage>http://www.mozilla.org/js/spidermonkey/</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>NPL-1.1</License>
        <IsA>library</IsA>
        <Summary>Stand-alone JavaScript C Library</Summary>
        <Description>Spidermonkey is Mozilla's C implementation of JavaScript.</Description>
        <Archive type="tarbz2" sha1sum="14367a7102ef2c54e0715bf16340fb4de9cb75ed">https://ftp.mozilla.org/pub/firefox/releases/38.8.0esr/source/firefox-38.8.0esr.source.tar.bz2</Archive>
        <BuildDependencies>
            <Dependency>zlib</Dependency>
            <Dependency>nspr</Dependency>
            <Dependency>readline</Dependency>
            <Dependency>libffi</Dependency>
        </BuildDependencies>
        <Patches>
            <!--Patch level="1">mozjs38-1269317.patch</Patch>
            <Patch level="1">mozjs38-add-bracket.patch</Patch>
            <Patch level="1">mozjs38-copy-headers.patch</Patch>
            <Patch level="1">mozjs38-fix-tracelogger.patch</Patch>
            <Patch level="1">mozjs38-install-name.patch</Patch>
            <Patch level="1">mozjs38-pkg-config-version.patch</Patch>
            <Patch level="1">mozjs38-shell-version.patch</Patch-->
        </Patches>
    </Source>

    <Package>
        <Name>mozjs38</Name>
        <RuntimeDependencies>
            <Dependency>nspr</Dependency>
            <Dependency>zlib</Dependency>
            <Dependency>readline</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="header">/usr/include</Path>
        </Files>
    </Package>


    <History>
        <Update release="1">
            <Date>2017-12-21</Date>
            <Version>38.2.8</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/desktop/kde/applications/kproperty/pspec.xml
<?xml version="1.0" ?> 
<!DOCTYPE PISI SYSTEM "https://raw.githubusercontent.com/LimeLinux/Packages/master/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>kproperty</Name>
        <Homepage>http://www.kexi-project.org/</Homepage>
        <Packager>
            <Name>lime Gnu/Linux Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPLv2+</License>
        <IsA>app:console</IsA>
        <Summary>A property editing framework with editor widget similar to what is known from Qt Designer</Summary>
        <Description>A property editing framework with editor widget similar to what is known from Qt Designer</Description>
        <Archive type="tarxz" sha1sum="9eb6b83c0bb5b62d9c219415bc05a5677fbc3ab3">http://download.kde.org/stable/kproperty/src/kproperty-3.0.0.tar.xz</Archive>
        <BuildDependencies>
            <Dependency>extra-cmake-modules</Dependency>
            <Dependency>qt5</Dependency>
            <Dependency>kconfig</Dependency>
            <Dependency>kcoreaddons</Dependency>
            <Dependency>kwidgetsaddons</Dependency>
            <Dependency>kguiaddons</Dependency>
            <Dependency>ki18n</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>kproperty</Name>
        <Summary>A property editing framework with editor widget similar to what is known from Qt Designer</Summary>
        <RuntimeDependencies>
            <Dependency>libgcc</Dependency>
            <Dependency>kconfig</Dependency>
            <Dependency>qt5</Dependency>
            <Dependency>kguiaddons</Dependency>
            <Dependency>kwidgetsaddons</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="header">/usr/include</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2017-01-04</Date>
            <Version>3.0.0</Version>
            <Comment>First release</Comment>
            <Name>lime Gnu/Linux Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/desktop/gnome3/base/zenity/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>zenity</Name>
        <Homepage>https://live.gnome.org/Zenity</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>LGPLv2</License>
        <IsA>app:gui</IsA>
        <Summary>A rewrite of gdialog</Summary>
        <Description>Zenity is the GNOME port of dialog which allows you to display dialog boxes from the commandline and shell scripts.</Description>
        <Archive sha1sum="52a167e8d0b10d351c71dbb3483b3cf11305c155" type="tarxz">https://git.gnome.org/browse/zenity/snapshot/zenity-3.24.0.tar.xz</Archive>
        <BuildDependencies>
            <Dependency>gtk3</Dependency>
            <Dependency>pango</Dependency>
            <Dependency>gnome-common</Dependency>
            <Dependency>gnome-doc-utils</Dependency>
            <Dependency>libnotify</Dependency>
            <Dependency>gdk-pixbuf</Dependency>
	        <Dependency>yelp-tools</Dependency>
	        <Dependency>yelp-xsl</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>zenity</Name>
        <RuntimeDependencies>
            <Dependency>gtk3</Dependency>
            <Dependency>pango</Dependency>
            <Dependency>libnotify</Dependency>
            <Dependency>gdk-pixbuf</Dependency>
	        <Dependency>yelp-tools</Dependency>
	        <Dependency>yelp-xsl</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="data">/usr/share/</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="config">/etc/xdg/menus</Path>
            <Path fileType="localedata">/usr/share/locale</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2017-03-01</Date>
            <Version>3.24.0</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/desktop/misc/lightdm/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>lightdm</Name>
        <Homepage>http://www.lxde.org</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPL2</License>
        <IsA>app</IsA>
        <Summary>LightDM Qt client library</Summary>
        <Description>LightDM Qt client library</Description>
        <Archive sha1sum="1e6ca409593cc437903c901496a7c2375d63f0e6" type="tarxz">https://launchpad.net/lightdm/1.15/1.15.0/+download/lightdm-1.15.0.tar.xz</Archive>
        <BuildDependencies>
            <Dependency>itstool</Dependency>
            <Dependency>intltool</Dependency>
            <Dependency>libxklavier</Dependency>
            <Dependency>xorg-server</Dependency>
            <Dependency>gobject-introspection</Dependency>
            <Dependency>gtk-doc</Dependency>
            <Dependency>libxml2</Dependency>
            <Dependency>pam</Dependency>
            <Dependency>libgcrypt</Dependency>
            <Dependency>gtk3</Dependency>
        </BuildDependencies>
        <Patches>
            <Patch level="1">lightdm-default-config.patch</Patch>
        </Patches>
    </Source>


    <Package>
        <Name>lightdm</Name>
        <Conflicts>
            <Package>lxdm</Package>
            <Package>sddm</Package>
        </Conflicts>
        <RuntimeDependencies>
            <Dependency>pam</Dependency>
            <Dependency>glib2</Dependency>
            <Dependency>libX11</Dependency>
            <Dependency>libxcb</Dependency>
            <Dependency>libXdmcp</Dependency>
            <Dependency>libgcrypt</Dependency>
            <Dependency>libxklavier</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="sysdir">/etc</Path>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="data">/usr/sbin</Path>
            <Path fileType="data">/usr/libexec</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="header">/usr/include</Path>
            <Path fileType="library">/usr/lib/pkgconfig</Path>
        </Files>

        <AdditionalFiles>
            <!--AdditionalFile target="/usr/share/polkit-1/rules.d/lightdm.rules" owner="root" permission="0644">lightdm.rules</AdditionalFile-->
            <AdditionalFile owner="root" permission="0644" target="/usr/lib/tmpfiles.d/lightdm.conf">lightdm.tmpfiles</AdditionalFile>
            <AdditionalFile owner="root" permission="0644" target="/etc/pam.d/lightdm">lightdm</AdditionalFile>
            <AdditionalFile owner="root" permission="0755" target="/usr/bin/wrapper">wrapper</AdditionalFile>
            <AdditionalFile owner="root" permission="0644" target="/usr/lib/systemd/system/lightdm.service">lightdm.service</AdditionalFile>
        </AdditionalFiles>

        <Provides>
            <!--COMAR script="service.py">System.Service</COMAR-->
            <COMAR script="package.py">System.Package</COMAR>
        </Provides>
    </Package>


    <History>
        <Update release="1">
            <Date>2016-12-21</Date>
            <Version>1.19.4</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/network/analyzer/libupnp/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>libupnp</Name>
        <Homepage>http://pupnp.sourceforge.net/</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>BSD</License>
        <IsA>library</IsA>
        <Summary>Portable UPnP library</Summary>
        <Description>The Universal Plug and Play (UPnP) SDK for Linux provides support for building UPnP-compliant control points, devices, and bridges on Linux.</Description>
        <Archive sha1sum="7983268c61126a4a9ab8757aa059f7f4c4cbc62d" type="tarbz2">https://sources.voidlinux.eu/libupnp-1.6.24/libupnp-1.6.24.tar.bz2</Archive>
        <BuildDependencies>
        </BuildDependencies>
        <Patches>
            <Patch level="1">pthread-flag.patch</Patch>
        </Patches>
    </Source>

    <Package>
        <Name>libupnp</Name>
        <Files>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="doc">/usr/share/doc</Path>
	    <Path fileType="header">/usr/include</Path>
        </Files>
    </Package>

    <History>
        <Update release="2">
            <Date>2018-02-28</Date>
            <Version>1.6.24</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/hardware/powermanagement/powertop/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>powertop</Name>
        <Homepage>http://www.lesswatts.org/projects/powertop/</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>app:console</IsA>
        <Summary>Power consumption monitor</Summary>
        <Description>PowerTOP is a Linux tool that finds the software component(s) that make your computer use more power than necessary while it is idle.</Description>
        <Archive sha1sum="60da464a0c5d39c64b5d4a0e854bc6c480f8927a" type="targz">https://01.org/sites/default/files/downloads/powertop/powertop-2.8.tar.gz</Archive>
        <BuildDependencies>
            <Dependency>libnl</Dependency>
            <Dependency>ncurses</Dependency>
            <Dependency>pciutils</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>powertop</Name>
        <RuntimeDependencies>
            <Dependency>libnl</Dependency>
            <Dependency>ncurses</Dependency>
            <Dependency>libgcc</Dependency>
            <Dependency>pciutils</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="man">/usr/share/man</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="executable">/usr/sbin</Path>
            <Path fileType="data">/var/cache/powertop</Path>
            <Path fileType="localedata">/usr/share/locale</Path>
        </Files>
    </Package>

    <History>
	    <Update release="2">
            <Date>2016-07-02</Date>
            <Version>2.8</Version>
            <Comment>First release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
        <Update release="1">
            <Date>2016-07-02</Date>
            <Version>2.8</Version>
            <Comment>First release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>
