=== LimeLinux/Packages/pisi-spec.dtd
<!-- Document Type Declaration file for PISI pspec.xml files -->
<!-- http://www.pardus.org.tr/projeler/pisi/ -->

<!ELEMENT PISI (Source,Package+,History)>

<!-- Source Section -->

<!ELEMENT Source (
	#PCDATA |
	Name |
	Homepage |
	Icon |
	Packager |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	Archive |
	Patches |
	BuildDependencies
)*>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT Homepage (#PCDATA)>

<!ELEMENT Icon (#PCDATA)>

<!ELEMENT Packager (Name, Email)>
<!ELEMENT Email (#PCDATA)>

<!ELEMENT License (#PCDATA)>

<!ELEMENT IsA (#PCDATA)>

<!ELEMENT PartOf (#PCDATA)>

<!ELEMENT Summary (#PCDATA)>
<!ATTLIST Summary xml:lang CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description xml:lang CDATA #IMPLIED>

<!ELEMENT Archive (#PCDATA)>
<!ATTLIST Archive sha1sum CDATA #REQUIRED>
<!-- NOTE: we can limit possible types here to the ones that pisi know -->
<!ATTLIST Archive type CDATA #REQUIRED>

<!ELEMENT BuildDependencies (Dependency*)>

<!ELEMENT Dependency (#PCDATA)>
<!ATTLIST Dependency versionFrom CDATA #IMPLIED>
<!ATTLIST Dependency versionTo CDATA #IMPLIED>
<!ATTLIST Dependency version CDATA #IMPLIED>
<!ATTLIST Dependency releaseFrom CDATA #IMPLIED>
<!ATTLIST Dependency releaseTo CDATA #IMPLIED>
<!ATTLIST Dependency release CDATA #IMPLIED>

<!ELEMENT Patches (Patch*)>

<!ELEMENT Patch (#PCDATA)>
<!ATTLIST Patch compressionType CDATA #IMPLIED>
<!ATTLIST Patch level CDATA #IMPLIED>
<!ATTLIST Patch target CDATA #IMPLIED>


<!-- Package Section -->

<!ELEMENT Package (
	#PCDATA |
	Name |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	RuntimeDependencies |
	Files |
	Conflicts |
	Replaces |
	AdditionalFiles |
	Provides
)*>

<!ELEMENT Provides (COMAR)+>
<!ELEMENT COMAR (#PCDATA)>
<!ATTLIST COMAR script CDATA #IMPLIED>

<!ELEMENT Conflicts (Package)+>
<!-- we have a problem here, this Package tag only contains a package name
while dtd treats this as another Package section, who said dtd doesnt
suck anyway -->
<!ATTLIST Package versionFrom CDATA #IMPLIED>
<!ATTLIST Package versionTo CDATA #IMPLIED>
<!ATTLIST Package version CDATA #IMPLIED>
<!ATTLIST Package releaseFrom CDATA #IMPLIED>
<!ATTLIST Package releaseTo CDATA #IMPLIED>
<!ATTLIST Package release CDATA #IMPLIED>

<!ELEMENT Replaces (Package)+>

<!ELEMENT AdditionalFiles (AdditionalFile+)>
<!ELEMENT AdditionalFile (#PCDATA)>
<!ATTLIST AdditionalFile target CDATA #REQUIRED>
<!ATTLIST AdditionalFile permission CDATA #IMPLIED>
<!ATTLIST AdditionalFile owner CDATA #IMPLIED>

<!ELEMENT RuntimeDependencies (Dependency*)>

<!ELEMENT Files (Path)+>

<!ELEMENT Path (#PCDATA)>
<!-- NOTE: is this list correct? -->
<!ATTLIST Path fileType
	(executable|library|data|config|doc|man|info|localedata|header)
	#REQUIRED>
<!ATTLIST Path permanent (false|true) #IMPLIED>


<!-- History Section -->

<!ELEMENT History (Update+)>

<!ELEMENT Update (#PCDATA | Date | Version | Comment | Name | Email)*>
<!ATTLIST Update release CDATA #REQUIRED>
<!ATTLIST Update type (security|bug) #IMPLIED>

<!ELEMENT Date (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT Comment (#PCDATA)>

=== LimeLinux/Packages/desktop/kde/framework/partitionmanager/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>partitionmanager</Name>
        <Homepage>http://www.kde.org</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>LGPLv2</License>
        <IsA>app:gui</IsA>
        <Summary>KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer</Summary>
        <Description>It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions..</Description>
        <Archive sha1sum="152eddcb7be7b9f6271019fdfdc18ada9547628f" type="tarxz">mirrors://kde/stable/partitionmanager/3.0.0/src/partitionmanager-3.0.0.tar.xz</Archive>
        <BuildDependencies>
            <Dependency>qt5</Dependency>
            <Dependency>libgcc</Dependency>
            <Dependency>util-linux</Dependency>
            <Dependency>kio</Dependency>
            <Dependency>ki18n</Dependency>
            <Dependency>kconfig</Dependency>
            <Dependency>kxmlgui</Dependency>
            <Dependency>kservice</Dependency>
            <Dependency>kcoreaddons</Dependency>
            <Dependency>kiconthemes</Dependency>
            <Dependency>kjobwidgets</Dependency>
            <Dependency>kconfigwidgets</Dependency>
            <Dependency>kwidgetsaddons</Dependency>
            <Dependency>kpmcore</Dependency>
            <Dependency>kcrash</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>partitionmanager</Name>
        <RuntimeDependencies>
            <Dependency>qt5</Dependency>
            <Dependency>libgcc</Dependency>
            <Dependency>util-linux</Dependency>
            <Dependency>kio</Dependency>
            <Dependency>ki18n</Dependency>
            <Dependency>kconfig</Dependency>
            <Dependency>kxmlgui</Dependency>
            <Dependency>kservice</Dependency>
            <Dependency>kcoreaddons</Dependency>
            <Dependency>kiconthemes</Dependency>
            <Dependency>kjobwidgets</Dependency>
            <Dependency>kconfigwidgets</Dependency>
            <Dependency>kwidgetsaddons</Dependency>
            <Dependency>kpmcore</Dependency>
            <Dependency>kcrash</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="library">/usr/lib/qt5</Path>
            <Path fileType="doc">/usr/share/doc</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2016-12-20</Date>
            <Version>3.0.0</Version>
            <Comment>First release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/system/base/libxml2/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>libxml2</Name>
        <Homepage>http://www.xmlsoft.org/</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>MIT</License>
        <IsA>library</IsA>
        <Summary>Version 2 of the library to manipulate XML files</Summary>
        <Description>Libxml2 is the XML C parser and toolkit developed for the Gnome project (but usable outside of the Gnome platform).</Description>
        <Archive sha1sum="958ae70baf186263a4bd801a81dd5d682aedd1db" type="targz">ftp://xmlsoft.org/libxml2/libxml2-2.9.4.tar.gz</Archive>
        <BuildDependencies>
            <Dependency>xz</Dependency>
            <Dependency>zlib</Dependency>
            <Dependency>readline</Dependency>
        </BuildDependencies>
    </Source>


    <Package>
        <Name>libxml2</Name>
        <RuntimeDependencies>
            <Dependency>xz</Dependency>
            <Dependency>zlib</Dependency>
            <Dependency>readline</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="header">/usr/include</Path>
        </Files>
    </Package>


    <History>
        <Update release="1">
            <Date>2016-12-21</Date>
            <Version>2.9.4</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/server/bind/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://limelinux.org/projeler/pisi/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>bind</Name>
        <Homepage>http://www.isc.org/products/BIND/bind9.html</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>as-is</License>
        <IsA>service</IsA>
        <Summary>The Berkeley Internet Name Domain (BIND) DNS (Domain Name System) server</Summary>
        <Description>bind is an implementation of the DNS protocols, bind includes a DNS server (named), a resolver library and tools for verifying that the DNS server is operating properly.</Description>
        <Archive sha1sum="4ddb2670976c06af7e86352616383958d82c51ce" type="targz">ftp://ftp.isc.org/isc/bind9/9.10.2/bind-9.10.2.tar.gz</Archive>
        <BuildDependencies>
            <Dependency>openssl</Dependency>
            <Dependency>libxml2</Dependency>
            <Dependency>libcap</Dependency>
            <Dependency>zlib</Dependency>
            <Dependency>e2fsprogs</Dependency>
            <Dependency>readline</Dependency>
            <Dependency>geoip</Dependency>
        </BuildDependencies>
        <Patches>
            <Patch level="1">nslookup-limelinux.patch</Patch>
            <Patch level="1">fedora/bind-9.5-PIE.patch</Patch>
            <Patch level="1">fedora/bind-9.5-parallel-build.patch</Patch>
            <Patch level="1">fedora/bind-96-libtool2.patch</Patch>
            <Patch level="1">fedora/bind-95-rh452060.patch</Patch>
            <Patch level="0">fedora/bind93-rh490837.patch</Patch>
            <Patch level="1">fedora/bind97-rh478718.patch</Patch>
            <Patch level="1">fedora/bind97-rh645544.patch</Patch>
            <Patch level="1">fedora/bind97-rh693982.patch</Patch>
        </Patches>
    </Source>

    <Package>
        <Name>bind-libs</Name>
        <IsA>library</IsA>
        <PartOf>server.library</PartOf>
        <Summary>bind-libs contains the libraries used by both the bind server package and the tools package</Summary>
        <RuntimeDependencies>
            <Dependency>openssl</Dependency>
            <Dependency>libxml2</Dependency>
            <Dependency>mit-kerberos</Dependency>
        </RuntimeDependencies>
	    <Files>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="header">/usr/include</Path>
            <Path fileType="executable">/usr/bin/isc-config.sh</Path>
            <Path fileType="man">/usr/share/man/man1/isc-config*</Path>
            <Path fileType="man">/usr/share/man/man3/lwres*</Path>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="man">/usr/share/man/man1</Path>
            <Path fileType="config">/etc/rsyslog.d/bind_chroot.conf</Path>
            <Path fileType="config">/var/named/chroot/etc</Path>
            <Path fileType="data">/var/named/chroot</Path>
        </Files>
        <AdditionalFiles>
            <AdditionalFile target="/etc/rsyslog.d/bind_chroot.conf" owner="root" group="root" permission="0644">chroot.rsyslog</AdditionalFile>
        </AdditionalFiles>
        <Provides>
            <COMAR script="chroot_package.py">System.Package</COMAR>
            <COMAR script="chroot_service.py">System.Service</COMAR>
        </Provides>
    </Package>

    <Package>
        <Name>bind</Name>
        <IsA>service</IsA>
        <RuntimeDependencies>
            <Dependency release="current">bind-libs</Dependency>
            <Dependency>libcap</Dependency>
            <Dependency>libxml2</Dependency>
            <Dependency>openssl</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="config">/etc</Path>
            <Path fileType="executable">/usr/sbin</Path>
            <Path fileType="data">/var</Path>
            <Path fileType="man">/usr/share/man/man3</Path>
            <Path fileType="man">/usr/share/man/man5</Path>
            <Path fileType="man">/usr/share/man/man8</Path>
            <Path fileType="doc">/usr/share/doc</Path>
        </Files>
        <AdditionalFiles>
            <AdditionalFile owner="root" permission="0644" target="/etc/bind/named.conf">named.conf</AdditionalFile>
            <AdditionalFile owner="root" permission="0644" target="/etc/conf.d/named">named.confd</AdditionalFile>
            <AdditionalFile owner="root" permission="0644" target="/var/named/named.ca">gentoo/named.ca</AdditionalFile>
            <AdditionalFile owner="root" permission="0644" target="/var/named/pri/127.zone">gentoo/127.zone</AdditionalFile>
            <AdditionalFile owner="root" permission="0644" target="/var/named/pri/localhost.zone">gentoo/localhost.zone</AdditionalFile>
            <AdditionalFile owner="root" permission="0644" target="/etc/logrotate.d/named">fedora/named.logrotate</AdditionalFile>
        </AdditionalFiles>
        <Provides>
            <!--COMAR script="service.py">System.Service</COMAR-->
            <COMAR script="bind_package.py">System.Package</COMAR>
        </Provides>
    </Package>

    <History>
        <Update release="1">
            <Date>2016-06-08</Date>
            <Version>9.10.2</Version>
            <Comment>First release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/programming/language/python/python-scapy/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>python-scapy</Name>
        <Homepage>http://www.secdev.org/projects/scapy/files</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>app:console</IsA>
        <IsA>library</IsA>
        <Summary>Powerful interactive packet manipulation program</Summary>
        <Description>Powerful interactive packet manipulation program</Description>
        <Archive sha1sum="ae0a9947a08a01a84abde9db12fed074ac888e47" type="targz">http://www.secdev.org/projects/scapy/files/scapy-2.2.0.tar.gz</Archive>
    </Source>

    <Package>
        <Name>python-scapy</Name>
        <RuntimeDependencies>
            <Dependency>python-pycrypto</Dependency>
            <Dependency>python-gnuplot-py</Dependency>
            <Dependency>gnuplot</Dependency>
            <Dependency>graphviz</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="man">/usr/share/man</Path>
            <Path fileType="doc">/usr/share/doc</Path>
        </Files>
    </Package>

    <History>
        <Update release="2">
            <Date>2016-12-21</Date>
            <Version>2.2.0</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/x11/terminal/xterm/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>xterm</Name>
        <Homepage>http://invisible-island.net/xterm</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>MIT</License>
        <Icon>terminal</Icon>
        <IsA>app:gui</IsA>
        <Summary>Terminal emulator for the X Window System</Summary>
        <Description>The xterm program is a terminal emulator for the X Window System. It provides DEC VT102 and Tektronix 4014 compatible terminals for programs that can't use the window system directly.</Description>
        <Archive sha1sum="0b648aaba45715c156a25e7ff629c82eb9836bc0" type="targz">ftp://ftp.invisible-island.net/xterm/xterm-330.tgz</Archive>
        <BuildDependencies>
            <Dependency>fontconfig</Dependency>
            <Dependency>libICE</Dependency>
            <Dependency>libXaw</Dependency>
            <Dependency>libXft</Dependency>
            <Dependency>libXmu</Dependency>
            <Dependency>libXt</Dependency>
            <Dependency>xorg-app</Dependency>
            <Dependency>libXpm</Dependency>
            <Dependency>libX11</Dependency>
        </BuildDependencies>
        <Patches>
<!--             <Patch level="1">xterm-226-man-page_paths.patch</Patch> -->
<!--             <Patch level="1">xterm-238-windowfontops.patch</Patch> -->

            <!-- ftp://invisible-island.net/xterm/16colors.txt -->
            <Patch>16colors.txt.diff</Patch>

            <!-- Default resources for Pardus -->
            <Patch>defaults.patch</Patch>
        </Patches>
    </Source>

    <Package>
        <Name>xterm</Name>
        <RuntimeDependencies>
            <Dependency>fontconfig</Dependency>
            <Dependency>libXinerama</Dependency>
            <Dependency>utempter</Dependency>
            <Dependency>libICE</Dependency>
            <Dependency>libXaw</Dependency>
            <Dependency>libXft</Dependency>
            <Dependency>libXmu</Dependency>
            <Dependency>libXt</Dependency>
            <Dependency>xorg-app</Dependency>
            <Dependency>libXpm</Dependency>
            <Dependency>libX11</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="data">/usr/share/X11</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="man">/usr/share/man</Path>
        </Files>
    </Package>

    <History>
        <Update release="2">
            <Date>2017-10-01</Date>
            <Version>330</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/desktop/kde/frameworks/kitemviews/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>kitemviews</Name>
        <Homepage>http://www.kde.org</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>LGPLv2</License>
        <IsA>library</IsA>
        <IsA>app:console</IsA>
        <Summary>Set of item models extending the Qt model-view framework</Summary>
        <Description>KItemViews includes a set of views, which can be used with item models. It includes views for categorizing lists and to add search filters to flat and hierarchical lists.</Description>
        <Archive sha1sum="2bea57d87dcaf06d6d23f154df9e690e93cde95d" type="tarxz">mirrors://kde/stable/frameworks/5.33/kitemviews-5.33.0.tar.xz</Archive>
        <BuildDependencies>
            <Dependency>qt5</Dependency>
            <Dependency>extra-cmake-modules</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>kitemviews</Name>
        <RuntimeDependencies>
            <Dependency>qt5</Dependency>
            <Dependency>libgcc</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="localedata">/usr/share/locale</Path>
            <Path fileType="library">/usr/lib/qt5</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="header">/usr/include</Path>
            <Path fileType="data">/usr/lib/cmake</Path>
            <Path fileType="config">/usr/lib/pkgconfig</Path>
        </Files>
    </Package>

    <History>
        <Update release="2">
            <Date>2017-05-05</Date>
            <Version>5.33.0</Version>
            <Comment>Version bump.</Comment>
            <Name>mahlas temir</Name>
            <Email>mahlastemir@gmail.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/hardware/disk/mtools/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>mtools</Name>
        <Homepage>http://mtools.linux.lu/</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>app:console</IsA>
        <Summary>Utilities to access MS-DOS disks without mounting them</Summary>
        <Description>Mtools are utilities to access MS-DOS disks without mounting them.</Description>
        <Archive sha1sum="d703db71a409837a37db10a09ef63a35183f7565" type="targz">mirrors://gnu/mtools/mtools-4.0.18.tar.gz</Archive>
    </Source>

    <Package>
        <Name>mtools</Name>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="config">/etc</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="info">/usr/share/info</Path>
            <Path fileType="man">/usr/share/man</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2016-12-21</Date>
            <Version>4.0.18</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/system/base/libgcrypt/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>libgcrypt</Name>
        <Homepage>http://www.gnupg.org/</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>LGPLv2.1</License>
        <IsA>library</IsA>
        <Summary>General purpose crypto library</Summary>
        <Description>Libgcrypt is a general purpose crypto library based on the code used in GNU Privacy Guard.</Description>
        <Archive sha1sum="85a6a936bcab4c3c05f5efbf6ce847f23d35c0c4" type="tarbz2">https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.7.2.tar.bz2</Archive>
        <BuildDependencies>
            <Dependency>libgpg-error</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>libgcrypt</Name>
        <RuntimeDependencies>
            <Dependency>libgpg-error</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="config">/etc/gcrypt</Path>
            <Path fileType="info">/usr/share/info</Path>
            <Path fileType="header">/usr/include</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2016-12-21</Date>
            <Version>1.7.2</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>
