=== LimeLinux/Packages/pisi-spec.dtd
<!-- Document Type Declaration file for PISI pspec.xml files -->
<!-- http://www.pardus.org.tr/projeler/pisi/ -->

<!ELEMENT PISI (Source,Package+,History)>

<!-- Source Section -->

<!ELEMENT Source (
	#PCDATA |
	Name |
	Homepage |
	Icon |
	Packager |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	Archive |
	Patches |
	BuildDependencies
)*>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT Homepage (#PCDATA)>

<!ELEMENT Icon (#PCDATA)>

<!ELEMENT Packager (Name, Email)>
<!ELEMENT Email (#PCDATA)>

<!ELEMENT License (#PCDATA)>

<!ELEMENT IsA (#PCDATA)>

<!ELEMENT PartOf (#PCDATA)>

<!ELEMENT Summary (#PCDATA)>
<!ATTLIST Summary xml:lang CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description xml:lang CDATA #IMPLIED>

<!ELEMENT Archive (#PCDATA)>
<!ATTLIST Archive sha1sum CDATA #REQUIRED>
<!-- NOTE: we can limit possible types here to the ones that pisi know -->
<!ATTLIST Archive type CDATA #REQUIRED>

<!ELEMENT BuildDependencies (Dependency*)>

<!ELEMENT Dependency (#PCDATA)>
<!ATTLIST Dependency versionFrom CDATA #IMPLIED>
<!ATTLIST Dependency versionTo CDATA #IMPLIED>
<!ATTLIST Dependency version CDATA #IMPLIED>
<!ATTLIST Dependency releaseFrom CDATA #IMPLIED>
<!ATTLIST Dependency releaseTo CDATA #IMPLIED>
<!ATTLIST Dependency release CDATA #IMPLIED>

<!ELEMENT Patches (Patch*)>

<!ELEMENT Patch (#PCDATA)>
<!ATTLIST Patch compressionType CDATA #IMPLIED>
<!ATTLIST Patch level CDATA #IMPLIED>
<!ATTLIST Patch target CDATA #IMPLIED>


<!-- Package Section -->

<!ELEMENT Package (
	#PCDATA |
	Name |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	RuntimeDependencies |
	Files |
	Conflicts |
	Replaces |
	AdditionalFiles |
	Provides
)*>

<!ELEMENT Provides (COMAR)+>
<!ELEMENT COMAR (#PCDATA)>
<!ATTLIST COMAR script CDATA #IMPLIED>

<!ELEMENT Conflicts (Package)+>
<!-- we have a problem here, this Package tag only contains a package name
while dtd treats this as another Package section, who said dtd doesnt
suck anyway -->
<!ATTLIST Package versionFrom CDATA #IMPLIED>
<!ATTLIST Package versionTo CDATA #IMPLIED>
<!ATTLIST Package version CDATA #IMPLIED>
<!ATTLIST Package releaseFrom CDATA #IMPLIED>
<!ATTLIST Package releaseTo CDATA #IMPLIED>
<!ATTLIST Package release CDATA #IMPLIED>

<!ELEMENT Replaces (Package)+>

<!ELEMENT AdditionalFiles (AdditionalFile+)>
<!ELEMENT AdditionalFile (#PCDATA)>
<!ATTLIST AdditionalFile target CDATA #REQUIRED>
<!ATTLIST AdditionalFile permission CDATA #IMPLIED>
<!ATTLIST AdditionalFile owner CDATA #IMPLIED>

<!ELEMENT RuntimeDependencies (Dependency*)>

<!ELEMENT Files (Path)+>

<!ELEMENT Path (#PCDATA)>
<!-- NOTE: is this list correct? -->
<!ATTLIST Path fileType
	(executable|library|data|config|doc|man|info|localedata|header)
	#REQUIRED>
<!ATTLIST Path permanent (false|true) #IMPLIED>


<!-- History Section -->

<!ELEMENT History (Update+)>

<!ELEMENT Update (#PCDATA | Date | Version | Comment | Name | Email)*>
<!ATTLIST Update release CDATA #REQUIRED>
<!ATTLIST Update type (security|bug) #IMPLIED>

<!ELEMENT Date (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT Comment (#PCDATA)>

=== LimeLinux/Packages/multimedia/video/gst-plugins-good-next/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>gst-plugins-good-next</Name>
        <Homepage>http://gstreamer.net/</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>library</IsA>
        <Summary>A set of good-quality plugins for GStreamer</Summary>
        <Description>gst-plugins-good contains a set of mature plugins and elements for GStreamer.</Description>
        <Archive sha1sum="201db5fe223325feaf79a256588d526df0a7d57f" type="tarxz">https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.8.1.tar.xz</Archive>
        <BuildDependencies>
            <Dependency>gst-plugins-base-next</Dependency>
            <Dependency>pulseaudio</Dependency>
            <Dependency>gstreamer-next</Dependency>
            <Dependency>libjpeg-turbo</Dependency>
            <Dependency>gdk-pixbuf</Dependency>
            <Dependency>libraw1394</Dependency>
            <Dependency>libXdamage</Dependency>
            <Dependency>libXfixes</Dependency>
            <Dependency>libsoup</Dependency>
            <Dependency>libXext</Dependency>
            <Dependency>libv4l</Dependency>
            <Dependency>libXv</Dependency>
            <Dependency>cairo</Dependency>
            <Dependency>aalib</Dependency>
            <Dependency>speex</Dependency>
            <Dependency>gtk2</Dependency>
            <Dependency>flac</Dependency>
            <Dependency>orc</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>gst-plugins-good-next</Name>
        <RuntimeDependencies>
            <Dependency>orc</Dependency>
            <Dependency>flac</Dependency>
            <Dependency>zlib</Dependency>
            <Dependency>speex</Dependency>
            <Dependency>libX11</Dependency>
            <Dependency>libpng</Dependency>
            <Dependency>cairo</Dependency>
            <Dependency>glib2</Dependency>
            <Dependency>aalib</Dependency>
            <Dependency>bzip2</Dependency>
            <Dependency>libv4l</Dependency>
            <Dependency>libXext</Dependency>
            <Dependency>libsoup</Dependency>
            <Dependency>libXfixes</Dependency>
            <Dependency>gdk-pixbuf</Dependency>
            <Dependency>libXdamage</Dependency>
            <Dependency>libjpeg-turbo</Dependency>
            <Dependency>gstreamer-next</Dependency>
            <Dependency>pulseaudio</Dependency>
            <Dependency>gst-plugins-base-next</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="config">/etc/gconf</Path>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="data">/usr/share/gstreamer-1.0/presets</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="doc">/usr/share/gtk-doc</Path>
            <Path fileType="man">/usr/share/man</Path>
            <Path fileType="localedata">/usr/share/locale</Path>
        </Files>
    </Package>

    <History>
        <Update release="2">
            <Date>2017-06-10</Date>
            <Version>1.8.1</Version>
            <Comment>First release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
        <Update release="1">
            <Date>2016-06-10</Date>
            <Version>1.8.1</Version>
            <Comment>First release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/desktop/kde/applications/kmix/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "https://raw.githubusercontent.com/LimeLinux/Packages/master/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>kmix</Name>
        <Homepage>http://kde.org/applications/multimedia/kmix/</Homepage>
        <Packager>
            <Name>lime Gnu/Linux Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPLv2</License>
        <Icon>kmix</Icon>
        <IsA>app:gui</IsA>
        <PartOf>desktop.kde.multimedia</PartOf>
        <Summary>KMix: KDE Digital Mixer</Summary>
        <Description>KMix: KDE Digital Mixer</Description>
        <Archive sha1sum="d79c7c4b00205f0f06602f494ae5a0f16337b474" type="tarxz">mirrors://kde/stable/applications/16.12.3/src/kmix-16.12.3.tar.xz</Archive>
        <BuildDependencies>
            <Dependency versionFrom="5.7.1">qt5</Dependency>
            <Dependency>extra-cmake-modules</Dependency>
            <Dependency>kdoctools</Dependency>
            <Dependency>kdelibs4-support</Dependency>
            <Dependency>ki18n</Dependency>
            <Dependency>kcmutils</Dependency>
            <Dependency>kemoticons</Dependency>
            <Dependency>kitemmodels</Dependency>
            <Dependency>kinit</Dependency>
            <Dependency>kunitconversion</Dependency>
            <Dependency>kdesignerplugin</Dependency>
            <Dependency>libcanberra</Dependency>
            <Dependency>glib2</Dependency>
            <Dependency>alsa-lib</Dependency>
            <Dependency>kglobalaccel</Dependency>
            <Dependency>plasma-framework</Dependency>
            <Dependency>extra-cmake-modules</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>kmix</Name>
        <RuntimeDependencies>
            <Dependency versionFrom="5.7.1">qt5</Dependency>
            <Dependency>alsa-lib</Dependency>
            <Dependency>libcanberra</Dependency>
            <Dependency>pulseaudio</Dependency>
            <Dependency>kdelibs4-support</Dependency>
            <Dependency>ki18n</Dependency>
            <Dependency>kconfig</Dependency>
            <Dependency>kxmlgui</Dependency>
            <Dependency>kcompletion</Dependency>
            <Dependency>kcoreaddons</Dependency>
            <Dependency>kdbusaddons</Dependency>
            <Dependency>kiconthemes</Dependency>
            <Dependency>kglobalaccel</Dependency>
            <Dependency>kwindowsystem</Dependency>
            <Dependency>kconfigwidgets</Dependency>
            <Dependency>knotifications</Dependency>
            <Dependency>kwidgetsaddons</Dependency>
            <Dependency>libgcc</Dependency>
            <Dependency>plasma-framework</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="config">/etc</Path>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="header">/usr/include</Path>
            <Path fileType="executable">/usr/bin</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2017-03-17</Date>
            <Version>16.12.3</Version>
            <Comment>First release</Comment>
            <Name>mahlas temir</Name>
            <Email>mahlastemir@gmail.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/programming/language/python/notify-python/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>notify-python</Name>
        <Homepage>http://www.galago-project.com</Homepage>
        <Packager>
            <Name>LimeLinux Community</Name>
            <Email>admins@pisilinux.org</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>app:console</IsA>
        <Summary>Python bindings for libnotify</Summary>
        <Description>notify-python are Python bindings for the Galago project's notification library libnotify.</Description>
        <Archive sha1sum="0e2b8525b1aabf0924c5efb53ced6aa429240ed0" type="targz">http://galago-project.org/files/releases/source/notify-python/notify-python-0.1.1.tar.gz</Archive>
        <BuildDependencies>
            <Dependency>libnotify</Dependency>
            <Dependency>python</Dependency>
            <Dependency>python-gtk</Dependency>
            <Dependency>gtk2</Dependency>
        </BuildDependencies>
        <Patches>
            <Patch level="1">link-with-python.patch</Patch>
            <Patch level="1">notify-python-0.1.1-fix-GTK-symbols.patch</Patch>
            <Patch level="1">libnotify0.7.patch</Patch>
        </Patches>
    </Source>

    <Package>
        <Name>notify-python</Name>
        <RuntimeDependencies>
            <Dependency>atk</Dependency>
            <Dependency>gtk2</Dependency>
            <Dependency>cairo</Dependency>
            <Dependency>glib2</Dependency>
            <Dependency>pango</Dependency>
            <Dependency>python</Dependency>
            <Dependency>freetype</Dependency>
            <Dependency>libnotify</Dependency>
            <Dependency>fontconfig</Dependency>
            <Dependency>gdk-pixbuf</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="data">/usr/lib/pkgconfig</Path>
            <Path fileType="data">/usr/share/pygtk/2.0/defs</Path>
        </Files>
    </Package>

    <History>
        <Update release="2">
            <Date>2017-01-09</Date>
            <Version>0.1.1</Version>
            <Comment>First release</Comment>
            <Name>Erg√ºn Salman</Name>
            <Email>poyraz76@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/desktop/gnome3/base/gnome-menus/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>gnome-menus</Name>
        <Homepage>http://www.gnome.org</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>app:gui</IsA>
        <Summary>Gnome Menus</Summary>
        <Description>gnome-menus has got desktop-directories, GNOME menus library and its python bindings.</Description>
        <Archive sha1sum="667e451d2a12395bf59606ecd4165df8143a76c6" type="tarxz">mirrors://gnome/gnome-menus/3.13/gnome-menus-3.13.3.tar.xz</Archive>
        <BuildDependencies>
            <Dependency>gnome-common</Dependency>
        </BuildDependencies>
        <Patches>
            <!--Patch level="1">gnome-menus-3.8.0-ignore_kde_standalone.patch</Patch-->
        </Patches>
    </Source>

    <Package>
        <Name>gnome-menus</Name>
        <RuntimeDependencies>
            <Dependency>gnome-common</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="config">/etc/xdg/menus</Path>
            <Path fileType="data">/usr/share/gir-1.0</Path>
            <Path fileType="localedata">/usr/share/locale</Path>
            <Path fileType="data">/usr/share/desktop-directories</Path>
            <Path fileType="header">/usr/include</Path>
            <Path fileType="library">/usr/lib/pkgconfig</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2016-07-26</Date>
            <Version>3.13.3</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/util/misc/lsof/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>lsof</Name>
        <Homepage>http://people.freebsd.org/~abe/</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>app:console</IsA>
        <Summary>Lists open files for running Unix processes</Summary>
        <Description>lsof is a Unix-specific diagnostic tool. Its name stands for LiSt Open Files, and it does just that. It lists information about any files that are open by processes currently running on the system. It can also list communications open by each process.</Description>
        <Archive sha1sum="9e260fb314272273965050064e9bcd636eb63388" type="tar">https://sourceforge.net/projects/limeteam/files/source-limelinux/lsof_4.89_src.tar</Archive>
    </Source>

    <Package>
        <Name>lsof</Name>
        <Files>
            <Path fileType="executable">/usr/sbin</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="data">/usr/share/lsof</Path>
            <Path fileType="man">/usr/share/man</Path>
        </Files>
    </Package>

    <History>
        <Update release="2">
            <Date>2018-02-28</Date>
            <Version>4.89</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/system/base/gperftools/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>gperftools</Name>
        <Homepage>https://github.com/gperftools/gperftools</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>BSD</License>
        <IsA>library</IsA>
        <IsA>app:console</IsA>
        <Summary>Google Performance Tools</Summary>
        <Description>Perf Tools is a collection of a high-performance multi-threaded malloc() implementation, plus some pretty nifty performance analysis tools.</Description>
        <Archive sha1sum="b7b0a24cbe052e0c4b69d43d7ecb5d8fca1dfa1c" type="targz">https://github.com/gperftools/gperftools/archive/gperftools-2.5.tar.gz</Archive>
    </Source>

    <Package>
        <Name>gperftools</Name>
        <RuntimeDependencies>
            <Dependency>libunwind</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="doc">/usr/share/doc/gperftools/COPYING</Path>
            <Path fileType="man">/usr/share/man</Path>
            <Path fileType="header">/usr/include</Path>
            <Path fileType="doc">/usr/share/doc/gperftools</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2016-12-21</Date>
            <Version>2.5</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/multimedia/misc/libbluray/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>libbluray</Name>
        <Homepage>http://www.videolan.org/developers/libbluray.html</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>LGPLv2</License>
        <IsA>library</IsA>
        <Summary>Library to access Blu-Ray disks for video playback</Summary>
        <Description>Libbluray package is aiming to provide a full portable free open source bluray library, which can be plugged into popular media players to allow full bluray navigation and playback on Linux. It will eventually be compatible with all current titles, and will be easily portable and embeddable in standard players such as mplayer and vlc.</Description>
        <Archive sha1sum="34eedb13e220eb88a5f58660bdb4e727e775fc83" type="tarbz2">ftp://ftp.videolan.org/pub/videolan/libbluray/0.9.2/libbluray-0.9.2.tar.bz2</Archive>
        <BuildDependencies>
            <Dependency>libtool</Dependency>
            <Dependency>doxygen</Dependency>
            <Dependency>pkgconfig</Dependency>
            <Dependency>libxml2</Dependency>
            <Dependency>freetype</Dependency>
            <Dependency>fontconfig</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>libbluray</Name>
        <RuntimeDependencies>
            <Dependency>libxml2</Dependency>
            <Dependency>freetype</Dependency>
            <Dependency>fontconfig</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
	    <Path fileType="data">/usr/share</Path>
	    <Path fileType="header">/usr/include</Path>
        </Files>
    </Package>


    <History>
        <Update release="1">
            <Date>2016-12-21</Date>
            <Version>0.9.2</Version>
            <Comment>First Release</Comment>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Update>
    </History>
</PISI>

=== LimeLinux/Packages/desktop/kde/frameworks/kdewebkit/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.limelinux.com/standard/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>kdewebkit</Name>
        <Homepage>http://www.kde.org</Homepage>
        <Packager>
            <Name>Lime GNU/LINUX Community</Name>
            <Email>admin@limelinux.com</Email>
        </Packager>
        <License>LGPLv2</License>
        <IsA>library</IsA>
        <IsA>app:console</IsA>
        <Summary>KDE5 WebKit integration</Summary>
        <Description>KdeWebkit provides KDE integration of the QtWebKit library.</Description>
        <Archive sha1sum="76198e4433ad4d37f4a4c0dce830af227e025ee8" type="tarxz">mirrors://kde/stable/frameworks/5.38/kdewebkit-5.38.0.tar.xz</Archive>
        <BuildDependencies>
            <Dependency versionFrom="5.8">qt5</Dependency>
            <Dependency versionFrom="5.8">qt5-webkit</Dependency>
            <Dependency versionFrom="5.38.0">extra-cmake-modules</Dependency>
            <Dependency versionFrom="5.38.0">kconfig</Dependency>
            <Dependency versionFrom="5.38.0">kcoreaddons</Dependency>
            <Dependency versionFrom="5.38.0">kio</Dependency>
            <Dependency versionFrom="5.38.0">kjobwidgets</Dependency>
            <Dependency versionFrom="5.38.0">kparts</Dependency>
            <Dependency versionFrom="5.38.0">kservice</Dependency>
            <Dependency versionFrom="5.38.0">kwallet</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>kdewebkit</Name>
        <RuntimeDependencies>
            <Dependency versionFrom="5.8">qt5</Dependency>
            <Dependency versionFrom="5.8">qt5-webkit</Dependency>
            <Dependency>libgcc</Dependency>
            <Dependency versionFrom="5.38.0">kconfig</Dependency>
            <Dependency versionFrom="5.38.0">kjobwidgets</Dependency>            
            <Dependency versionFrom="5.38.0">kcoreaddons</Dependency>
            <Dependency versionFrom="5.38.0">kparts</Dependency>
            <Dependency versionFrom="5.38.0">kservice</Dependency>
            <Dependency versionFrom="5.38.0">kwallet</Dependency>
            <Dependency versionFrom="5.38.0">kio</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="library">/usr/lib/qt5</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="data">/usr/mkspecs/modules/</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="header">/usr/include</Path>
            <Path fileType="data">/usr/lib/cmake</Path>
            <Path fileType="config">/usr/lib/pkgconfig</Path>
        </Files>
    </Package>

    <History>
        <Update release="4">
            <Date>2017-09-12</Date>
            <Version>5.38.0</Version>
            <Comment>Version bump.</Comment>
            <Name>mahlas temir</Name>
            <Email>mahlastemir@gmail.com</Email>
        </Update>
    </History>
</PISI>
